export default {
  GET_TRIP_LIST_ATTEMPT: 'GET_TRIP_LIST_ATTEMPT',
  GET_TRIP_LIST_SUCCESS: 'GET_TRIP_LIST_SUCCESS',
  GET_TRIP_LIST_ERROR: 'GET_TRIP_LIST_ERROR',

  GET_TRIP_BY_ID_ATTEMPT: 'GET_TRIP_BY_ID_ATTEMPT',
  GET_TRIP_BY_ID_SUCCESS: 'GET_TRIP_BY_ID_SUCCESS',
  GET_TRIP_BY_ID_ERROR: 'GET_TRIP_BY_ID_ERROR',

  GET_ORDER_BY_ID_ATTEMPT: 'GET_ORDER_BY_ID_ATTEMPT',
  GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
  GET_ORDER_BY_ID_ERROR: 'GET_ORDER_BY_ID_ERROR',

  CONFIRM_ORDER_ATTEMPT: 'CONFIRM_ORDER_ATTEMPT',
  CONFIRM_ORDER_SUCCESS: 'CONFIRM_ORDER_SUCCESS',
  CONFIRM_ORDER_ERROR: 'CONFIRM_ORDER_ERROR',

  NEXT_CHECKOUT_SECTION: 'NEXT_CHECKOUT_SECTION',
  PREV_CHECKOUT_SECTION: 'PREV_CHECKOUT_SECTION',
  SET_CHECKOUT_STATE: 'SET_CHECKOUT_STATE',
  SET_CURRENT_SECTION: 'SET_HIGHEST_COMPLETED_SECTION',
  RESET_CHECKOUT: 'RESET_CHECKOUT',

  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  LOGOUT: 'LOGOUT',
};
