export default {
  GET_TRIP_DATA_ATTEMPT: 'GET_TRIP_DATA_ATTEMPT',
  GET_TRIP_DATA_SUCCESS: 'GET_TRIP_DATA_REQUEST_SUCCESS',
  GET_TRIP_DATA_ERROR: 'GET_TRIP_DATA_ERROR',

  NEXT_CHECKOUT_SECTION: 'NEXT_CHECKOUT_SECTION',
  SET_CHECKOUT_STATE: 'SET_CHECKOUT_STATE',
};
