export default {
  GET_TRIP_LIST_ATTEMPT: 'GET_TRIP_LIST_ATTEMPT',
  GET_TRIP_LIST_SUCCESS: 'GET_TRIP_LIST_SUCCESS',
  GET_TRIP_LIST_ERROR: 'GET_TRIP_LIST_ERROR',

  ADMIN_GET_TRIP_LIST_ATTEMPT: 'ADMIN_GET_TRIP_LIST_ATTEMPT',
  ADMIN_GET_TRIP_LIST_SUCCESS: 'ADMIN_GET_TRIP_LIST_SUCCESS',
  ADMIN_GET_TRIP_LIST_ERROR: 'ADMIN_GET_TRIP_LIST_ERROR',

  GET_TRIP_BY_ID_ATTEMPT: 'GET_TRIP_BY_ID_ATTEMPT',
  GET_TRIP_BY_ID_SUCCESS: 'GET_TRIP_BY_ID_SUCCESS',
  GET_TRIP_BY_ID_ERROR: 'GET_TRIP_BY_ID_ERROR',

  ADMIN_GET_TRIP_BY_ID_ATTEMPT: 'ADMIN_GET_TRIP_BY_ID_ATTEMPT',
  ADMIN_GET_TRIP_BY_ID_SUCCESS: 'ADMIN_GET_TRIP_BY_ID_SUCCESS',
  ADMIN_GET_TRIP_BY_ID_ERROR: 'ADMIN_GET_TRIP_BY_ID_ERROR',

  ADMIN_CREATE_TRIP_ATTEMPT: 'ADMIN_CREATE_TRIP_ATTEMPT',
  ADMIN_CREATE_TRIP_SUCCESS: 'ADMIN_CREATE_TRIP_SUCCESS',
  ADMIN_CREATE_TRIP_ERROR: 'ADMIN_CREATE_TRIP_ERROR',

  ADMIN_UPDATE_TRIP_ATTEMPT: 'ADMIN_UPDATE_TRIP_ATTEMPT',
  ADMIN_UPDATE_TRIP_SUCCESS: 'ADMIN_UPDATE_TRIP_SUCCESS',
  ADMIN_UPDATE_TRIP_ERROR: 'ADMIN_UPDATE_TRIP_ERROR',

  GET_ORDER_BY_ID_ATTEMPT: 'GET_ORDER_BY_ID_ATTEMPT',
  GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
  GET_ORDER_BY_ID_ERROR: 'GET_ORDER_BY_ID_ERROR',

  CONFIRM_ORDER_ATTEMPT: 'CONFIRM_ORDER_ATTEMPT',
  CONFIRM_ORDER_SUCCESS: 'CONFIRM_ORDER_SUCCESS',
  CONFIRM_ORDER_ERROR: 'CONFIRM_ORDER_ERROR',

  ADMIN_GET_UNPAID_ORDERS_ATTEMPT: 'ADMIN_GET_UNPAID_ORDERS_ATTEMPT',
  ADMIN_GET_UNPAID_ORDERS_SUCCESS: 'ADMIN_GET_UNPAID_ORDERS_SUCCESS',
  ADMIN_GET_UNPAID_ORDERS_ERROR: 'ADMIN_GET_UNPAID_ORDERS_ERROR',

  ADMIN_UPDATE_ORDER_ATTEMPT: 'ADMIN_UPDATE_ORDER_ATTEMPT',
  ADMIN_UPDATE_ORDER_SUCCESS: 'ADMIN_UPDATE_ORDER_SUCCESS',
  ADMIN_UPDATE_ORDER_ERROR: 'ADMIN_UPDATE_ORDER_ERROR',

  NEXT_CHECKOUT_SECTION: 'NEXT_CHECKOUT_SECTION',
  PREV_CHECKOUT_SECTION: 'PREV_CHECKOUT_SECTION',
  SET_CHECKOUT_STATE: 'SET_CHECKOUT_STATE',
  SET_CURRENT_SECTION: 'SET_HIGHEST_COMPLETED_SECTION',
  RESET_CHECKOUT: 'RESET_CHECKOUT',

  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  ADMIN_GET_MEMBER_BY_ID_ATTEMPT: 'ADMIN_GET_MEMBER_BY_ID_ATTEMPT',
  ADMIN_GET_MEMBER_BY_ID_SUCCESS: 'ADMIN_GET_MEMBER_BY_ID_SUCCESS',
  ADMIN_GET_MEMBER_BY_ID_ERROR: 'ADMIN_GET_MEMBER_BY_ID_ERROR',

  ADMIN_GET_MEMBER_LIST_ATTEMPT: 'ADMIN_GET_MEMBER_LIST_ATTEMPT',
  ADMIN_GET_MEMBER_LIST_SUCCESS: 'ADMIN_GET_MEMBER_LIST_SUCCESS',
  ADMIN_GET_MEMBER_LIST_ERROR: 'ADMIN_GET_MEMBER_LIST_ERROR',

  CREATE_MEMBER_ATTEMPT: 'CREATE_MEMBER_ATTEMPT',
  CREATE_MEMBER_SUCCESS: 'CREATE_MEMBER_SUCCESS',
  CREATE_MEMBER_ERROR: 'CREATE_MEMBER_ERROR',

  ADMIN_UPDATE_MEMBER_ATTEMPT: 'ADMIN_UPDATE_MEMBER_ATTEMPT',
  ADMIN_UPDATE_MEMBER_SUCCESS: 'ADMIN_UPDATE_MEMBER_SUCCESS',
  ADMIN_UPDATE_MEMBER_ERROR: 'ADMIN_UPDATE_MEMBER_ERROR',

  LOGOUT: 'LOGOUT',
};
