export const RequestStatus = {
  UNITIALIZED: 'UNITIALIZED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export const DAY_PICKER_DATE_CORRECTION = 57600000;
export const TWELVE_HOUR_CORRECTION = 43200000;

export const GOOGLE_MAPS_API_KEY = 'AIzaSyAQWRkViWIB2ip6xADOnkfT6Tv2NoTcWB4';
