export const RequestStatus = {
  UNITIALIZED: 'UNITIALIZED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export const DAY_PICKER_DATE_CORRECTION = 57600000;

export const GOOGLE_MAPS_API_KEY = 'AIzaSyDDHSAqyK_6c7QwEF2tKAnGaY7Hk_7u-Bk';
